name: StyleCI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  style-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ ubuntu-latest ]
        php: [ 8.3 ]

    name: P${{ matrix.php }} - ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate composer.json and composer.lock
        run: composer validate --strict

      - name: Install PHP versions
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v3
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.json') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress --optimize-autoloader


      # Code quality
      - name: Execute Code Sniffer via phpcs
        run: |
          #          composer require --dev squizlabs/php_codesniffer
               vendor/bin/phpcbf --standard=PSR12 src || vendor/bin/phpcbf --standard=PSR12 src
               vendor/bin/phpcs --standard=PSR12 src
